# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/malata/smb_a1004/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/libaudio.so:obj/lib/libaudio.so \
    vendor/malata/smb_a1004/proprietary/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
    vendor/malata/smb_a1004/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/malata/smb_a1004/proprietary/libnvrm_graphics.so:obj/lib/libnvrm_graphics.so \
    vendor/malata/smb_a1004/proprietary/libnvddk_audiofx.so:obj/lib/libnvddk_audiofx.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_query.so:obj/lib/libnvodm_query.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_misc.so:obj/lib/libnvodm_misc.so \
    vendor/malata/smb_a1004/proprietary/libnvrm.so:obj/lib/libnvrm.so \
    vendor/malata/smb_a1004/proprietary/libnvos.so:obj/lib/libnvos.so \
    vendor/malata/smb_a1004/proprietary/libnvdispmgr_d.so:obj/lib/libnvdispmgr_d.so \
    vendor/malata/smb_a1004/proprietary/libnvdispatch_helper.so:obj/lib/libnvdispatch_helper.so \
    vendor/malata/smb_a1004/proprietary/libnvomxilclient.so:obj/lib/libnvomxilclient.so \
    vendor/malata/smb_a1004/proprietary/libgps.so:obj/lib/libgps.so

# Standard blobs necessary for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/libaudio.so:system/lib/libaudio.so \
    vendor/malata/smb_a1004/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/malata/smb_a1004/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/malata/smb_a1004/proprietary/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/malata/smb_a1004/proprietary/gles2_simplespin.so:system/lib/gles2_simplespin.so \
    vendor/malata/smb_a1004/proprietary/omxplayer.so:system/lib/omxplayer.so \
    vendor/malata/smb_a1004/proprietary/libhwmediarecorder.so:system/lib/libhwmediarecorder.so \
    vendor/malata/smb_a1004/proprietary/libhwmediaplugin.so:system/lib/libhwmediaplugin.so \
    vendor/malata/smb_a1004/proprietary/libgps.so:system/lib/libgps.so

# malata blobs for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/malata/smb_a1004/proprietary/libnvsm.so:system/lib/libnvsm.so \
    vendor/malata/smb_a1004/proprietary/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/malata/smb_a1004/proprietary/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/malata/smb_a1004/proprietary/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/malata/smb_a1004/proprietary/libnvdispatch_helper.so:system/lib/libnvdispatch_helper.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
    vendor/malata/smb_a1004/proprietary/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/malata/smb_a1004/proprietary/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/malata/smb_a1004/proprietary/libnvidia_graphics_jni.so:system/lib/libnvidia_graphics_jni.so \
    vendor/malata/smb_a1004/proprietary/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/malata/smb_a1004/proprietary/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/malata/smb_a1004/proprietary/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/malata/smb_a1004/proprietary/libnvmm.so:system/lib/libnvmm.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/malata/smb_a1004/proprietary/libnvomx.so:system/lib/libnvomx.so \
    vendor/malata/smb_a1004/proprietary/libnvos.so:system/lib/libnvos.so \
    vendor/malata/smb_a1004/proprietary/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
    vendor/malata/smb_a1004/proprietary/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/malata/smb_a1004/proprietary/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/malata/smb_a1004/proprietary/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/malata/smb_a1004/proprietary/libnvrm.so:system/lib/libnvrm.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/malata/smb_a1004/proprietary/libnvddk_aes_user.so:system/lib/libnvddk_aes_user.so \
    vendor/malata/smb_a1004/proprietary/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_videorenderer.so:system/lib/libnvmm_videorenderer.so \
    vendor/malata/smb_a1004/proprietary/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/malata/smb_a1004/proprietary/libnvec.so:system/lib/libnvec.so \
    vendor/malata/smb_a1004/proprietary/libpvnvomx.so:system/lib/libpvnvomx.so \
    vendor/malata/smb_a1004/proprietary/pvnvomx.cfg:system/etc/pvnvomx.cfg \
    vendor/malata/smb_a1004/proprietary/nvmm_jpegenc_test.so:system/lib/nvmm_jpegenc_test.so \
    vendor/malata/smb_a1004/proprietary/nvec_update_app.so:system/lib/nvec_update_app.so \
    vendor/malata/smb_a1004/proprietary/nvmm_videodec_test.so:system/lib/nvmm_videodec_test.so \
    vendor/malata/smb_a1004/proprietary/nvodm_imager_conformance.so:system/lib/nvodm_imager_conformance.so \
    vendor/malata/smb_a1004/proprietary/nvmm_videoenc_test.so:system/lib/nvmm_videoenc_test.so \
    vendor/malata/smb_a1004/proprietary/nvddk_2d_test_sanity.so:system/lib/nvddk_2d_test_sanity.so \
    vendor/malata/smb_a1004/proprietary/nvodm_focuser_conformance.so:system/lib/nvodm_focuser_conformance.so

# EGL files for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/malata/smb_a1004/proprietary/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/malata/smb_a1004/proprietary/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so

# HALs for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/malata/smb_a1004/proprietary/overlay.tegra.so:system/lib/hw/overlay.tegra.so \
    vendor/malata/smb_a1004/proprietary/lights.tegra.so:system/lib/hw/lights.tegra.so \
    vendor/malata/smb_a1004/proprietary/sensors.tegra.so:system/lib/hw/sensors.tegra.so

# Keychar files for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/nvec_keyboard.kcm.bin:system/usr/keychars/nvec_keyboard.kcm.bin \
    vendor/malata/smb_a1004/proprietary/usb_keyboard_102_en_us.kcm.bin:system/usr/keychars/usb_keyboard_102_en_us.kcm.bin \
    vendor/malata/smb_a1004/proprietary/tegra-kbc.kcm.bin:system/usr/keychars/tegra-kbc.kcm.bin \
    vendor/malata/smb_a1004/proprietary/gpio-keys.kcm.bin:system/usr/keychars/gpio-keys.kcm.bin

# Keylayout files for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/gpio-keys.kl:system/usr/keychars/gpio-keys.kl \
    vendor/malata/smb_a1004/proprietary/nvec_keyboard.kl:system/usr/keychars/nvec_keyboard.kl \
    vendor/malata/smb_a1004/proprietary/tegra-kbc.kl:system/usr/keychars/tegra-kbc.kl \
    vendor/malata/smb_a1004/proprietary/usb_keyboard_102_en_us.kl:system/usr/keychars/usb_keyboard_102_en_us.kl

# bin files for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/nvmm_vc1dec.axf:system/bin/nvmm_vc1dec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_wmaprodec.axf:system/bin/nvmm_wmaprodec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_h264dec.axf:system/bin/nvmm_h264dec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_service.axf:system/bin/nvmm_service.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_adtsdec.axf:system/bin/nvmm_adtsdec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_wavdec.axf:system/bin/nvmm_wavdec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_reference.axf:system/bin/nvmm_reference.axf \
    vendor/malata/smb_a1004/proprietary/nv_hciattach:system/bin/nv_hciattach \
    vendor/malata/smb_a1004/proprietary/nvmm_sorensondec.axf:system/bin/nvmm_sorensondec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_mp3dec.axf:system/bin/nvmm_mp3dec.axf \
    vendor/malata/smb_a1004/proprietary/nvddk_audiofx_core.axf:system/bin/nvddk_audiofx_core.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_sw_mp3dec.axf:system/bin/nvmm_sw_mp3dec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_aacdec.axf:system/bin/nvmm_aacdec.axf \
    vendor/malata/smb_a1004/proprietary/nvrm_daemon:system/bin/nvrm_daemon \
    vendor/malata/smb_a1004/proprietary/nvmm_jpegenc.axf:system/bin/nvmm_jpegenc.axf \
    vendor/malata/smb_a1004/proprietary/nvdmmultidisplay:system/bin/nvdmmultidisplay \
    vendor/malata/smb_a1004/proprietary/nvddk_audiofx_transport.axf:system/bin/nvddk_audiofx_transport.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_mp2dec.axf:system/bin/nvmm_mp2dec.axf \
    vendor/malata/smb_a1004/proprietary/nvtest:system/bin/nvtest \
    vendor/malata/smb_a1004/proprietary/nvmm_mpeg4dec.axf:system/bin/nvmm_mpeg4dec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_wmadec.axf:system/bin/nvmm_wmadec.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_audiomixer.axf:system/bin/nvmm_audiomixer.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_manager.axf:system/bin/nvmm_manager.axf \
    vendor/malata/smb_a1004/proprietary/nvmm_jpegdec.axf:system/bin/nvmm_jpegdec.axf \
    vendor/malata/smb_a1004/proprietary/nvrm_avp.axf:system/bin/nvrm_avp.axf \
    vendor/malata/smb_a1004/proprietary/tegrastats:system/bin/tegrastats

# wifi/bt files for smb_a1004
PRODUCT_COPY_FILES += \
    vendor/malata/smb_a1004/proprietary/bluecore6.psr:system/etc/bluez/bluecore6.psr \
    vendor/malata/smb_a1004/proprietary/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
    vendor/malata/smb_a1004/proprietary/BCM4329B1.hcd:system/lib/hw/wlan/BCM4329B1.hcd \
    vendor/malata/smb_a1004/proprietary/nvram.txt:system/etc/firmware/nvram.txt \
    vendor/malata/smb_a1004/proprietary/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \
    vendor/malata/smb_a1004/proprietary/bc_hciattach:system/bin/bc_hciattach

# Stage Fright for smb_a1004
PRODUCT_COPY_FILES += \
   vendor/malata/smb_a1004/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so

# RIL for smb_a1004
PRODUCT_COPY_FILES += \
   vendor/malata/smb_a1004/proprietary/libmbm-ril.so:system/lib/libmbm-ril.so \
   vendor/malata/smb_a1004/proprietary/libril.so:system/lib/libril.so \
   vendor/malata/smb_a1004/proprietary/rild:system/bin/rild
